#!/bin/bash

echo "🚀 CabMate Finder Backend Deployment Guide"
echo "=========================================="
echo ""

echo "📋 Backend is ready for deployment!"
echo ""
echo "✅ Files prepared:"
echo "   - package.json (with dependencies)"
echo "   - server.js (Express server)"
echo "   - CORS configured for Vercel frontend"
echo "   - Health check endpoint"
echo ""

echo "🌐 Deployment Options:"
echo ""
echo "1. 🎯 RENDER (Recommended - Free tier available)"
echo "   - Go to: https://render.com"
echo "   - Sign up/login with GitHub"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Connect your GitHub repository"
echo "   - Select the 'backend' folder"
echo "   - Configure:"
echo "     • Build Command: npm install"
echo "     • Start Command: npm start"
echo "     • Environment: Node"
echo ""

echo "2. 🚂 RAILWAY"
echo "   - Go to: https://railway.app"
echo "   - Sign up/login with GitHub"
echo "   - Click 'New Project' → 'Deploy from GitHub repo'"
echo "   - Select your repository"
echo "   - Choose the 'backend' folder"
echo ""

echo "3. 🦅 FLY.IO (Requires credit card)"
echo "   - Go to: https://fly.io"
echo "   - Add payment information"
echo "   - Run: flyctl launch"
echo ""

echo "4. 🟣 HEROKU"
echo "   - Go to: https://heroku.com"
echo "   - Create new app"
echo "   - Connect GitHub repository"
echo "   - Deploy from 'backend' folder"
echo ""

echo "📝 After deployment:"
echo "1. Copy the backend URL (e.g., https://your-app.onrender.com)"
echo "2. Update frontend App.jsx to use the new URL"
echo "3. Test the full application"
echo ""

echo "🔧 Current backend configuration:"
echo "   - Port: 3001 (or process.env.PORT)"
echo "   - CORS: Configured for Vercel domains"
echo "   - API endpoint: /api/travel-data"
echo "   - Health check: /api/travel-data"
echo ""

echo "Ready to deploy! 🎉"
